theme: jekyll-theme-minimal
title: "Welcome to Netdisco!"
description: "Netdisco is a web-based network management tool suitable for small to very large networks. IP and MAC address data is collected into a PostgreSQL database using SNMP, CLI, or device APIs."
show_downloads: true
install_url: 'https://metacpan.org/pod/App::Netdisco'
config_url: 'https://github.com/netdisco/netdisco/wiki/Configuration'
demo_url: 'https://netdisco2-demo.herokuapp.com/'
wiki_url: 'https://github.com/netdisco/netdisco/wiki'
irc_url: 'https://webchat.freenode.net/?randomnick=1&prompt=1&channels=%23netdisco'
